/**
*   =====================================================================================
*   Class Name          : Constant
*   Description         : Constants used across the system
*   Author              : Sqware Peg - Purba Ghosh
*   Created On          : 16 Aug 2018
*   Modification Log    :
*   =====================================================================================
*   Developer       Date            Modification ID         Description
*   =====================================================================================
*   Purba Ghosh     16 Aug 2018     1000                    Initial version
*   =====================================================================================
*/

public with sharing class Constant {

    public static final String PPSR_ISSUES = 'PPSR Issues';
    public static final String RESERVE_PRICE = 'Reserve';
    public static final String RELEASE_FOR_SALE = 'Release';
    public static final String VALUE_NONE = 'None';
    public static final String NOT_APPLICABLE = 'Not Applicable';
    public static final String REPAIRABLE = 'Repairable';
    public static final String STATUTORY = 'Statutory';
    public static final String INSPECTED = 'Inspected';
    public static final String ALLOCATED_TO_AUCTION = 'Allocated to Auction';
    public static final String CLOSED_SERVICE_ONLY = 'Closed /Service only';
    public static final String NOT_RELEASED_SALE = 'Not released/Sale';
    public static final String UNDER_REFERRAL = 'Under referral';
    public static final String RELEASED_FOR_SALE = 'Released for Sale';
    public static final String RELEASED_FOR_SELLER = 'Returned to Seller';
    public static final String SOLD = 'Sold';
    public static final String UNSOLD = 'Unsold';
	public String blah = 'blah1';
            
    public Constant() {        
    }    
}